version: '3.7'
services:

  zookeeper:
    image: wurstmeister/zookeeper:latest

  local_kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: local_kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "kf-datalake-query-events:4:1:delete"
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --topic kf-datalake-query-events --describe"]
      start_period: 20s
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      - zookeeper

  datalakequeryingester:
    build: .
    image: datalakequeryingester:build
    ports:
      - 80:8080
    environment:
      KAFKA_BROKERS: "local_kafka:9092"
      DATALAKEQUERYINGESTER_KAFKA_TOPIC: "kf-datalake-query-events"
    depends_on:
      local_kafka:
        condition: "service_healthy"

  test:
    build: .
    volumes:
      - .:/datalakequeryingester
    entrypoint:
      - tox
    environment:
      PRE_COMMIT_HOME: ./.pre-commit
    depends_on:
      datalakequeryingester:
        condition: "service_healthy"
