version: 2.1
orbs:
  python: circleci/python@1.3.2
  aws-ecr: circleci/aws-ecr@6.15.3
jobs:
  build:
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run:
          name: install dependencies and run tests
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -e . --index-url https://pypi.org/simple/
            pip install tox --index-url https://pypi.org/simple/
  # Release a Docker base image.
  release_images:
    docker:
      - image: cimg/base:2022.02
    environment:
      AWS_REGION: us-west-2
      AWS_ECR_ACCOUNT_URL: 711570343235.dkr.ecr.us-west-2.amazonaws.com
    steps:
      - checkout
      - aws-ecr/ecr-login
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image and Push to ECR
          command: |
            REGISTRY=711570343235.dkr.ecr.us-west-2.amazonaws.com
            IMAGE_NAME=datalake-query-ingester
            if [[ -n "${CIRCLE_TAG}" ]]; then
              TAG="${CIRCLE_TAG}"
            else
              TAG="${CIRCLE_BRANCH}"
            fi
            # Build docker image and tag
            docker build -t "${IMAGE_NAME}:latest" .
            COMMIT=$(git rev-parse --short HEAD 2>/dev/null)
            docker tag "${IMAGE_NAME}:latest" "${REGISTRY}/${IMAGE_NAME}:${TAG}"
            docker tag "${IMAGE_NAME}:latest" "${REGISTRY}/${IMAGE_NAME}:${COMMIT}"
            docker push "${REGISTRY}/${IMAGE_NAME}:${TAG}"
            docker push "${REGISTRY}/${IMAGE_NAME}:${COMMIT}"
workflows:
  build-release:
    jobs:
      - build:
          context: Build
          filters:
            tags:
              only: /.*/

      - release_images:
          context: Deploy
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - /feature-.*/
            tags:
              only: /.*/
